<?php
/* 
 * $Id: config-core.php 22 2010-06-03 00:14:28Z veghead $
 * WARNING! Do not edit this file, it will be overwritten when you
 * upgrade.
 * Instead, make changes to config.php they will override 
 * the defaults here.
 */

// General options
$conf['app_title'] = 'Oliver';
$conf['vfstype'] = 'ftp';
$conf['ftp_server'] = 'localhost';
$conf['ftp_server_port'] = 21;
$conf['ftp_passive'] = true;
$conf['ftp_timeout'] = 90;
$conf['imgdir'] = 'graphics';
$conf['session_name']  =  'OLIVER';
$conf['motdfile'] = 'motd.php';
$conf['charset'] = 'UTF-8';
$conf['space_in_filename_workaround'] = true;

// Look in 'lang' directory for available translations
$conf['lang'] = 'en-uk';

// Set to false if you don't wish to allow users to choose their 
// language upon login
$conf['lang_ask'] = true;

// Shares, shortcuts, drives, areas...I don't care what you call them :)
// Don't delete this! If you don't want any, simply remove everything
// within the parentheses.
$conf['roots'] = array(
        'H Drive' => '/work',
        'I Drive' => '/inform',
        );


// Set to false if you don't wish to allow users to have direct
// links to files
$conf['enable_dlink'] = true;


// Set to false if you don't wish to allow users to change file
// modes
$conf['enable_chmod'] = true;


// Number of seconds before a session expires between
// accesses
$conf['session_timeout'] = 600;


// Set to false to disable logging
$conf['enable_logging'] = true;


// Set to an absolute pathname or the word 'syslog' if you 
// prefer to use syslog. 
$conf['logfile'] = 'syslog';


// Syslog facility to use
// accesses
$conf['syslog_facility'] = LOG_USER;


// Use this array to prevent certain filenames from 
// being displayed. The key is the filename and the value should be 
// a description.
$conf['veto_filenames'] = array(
    'Network Trash Folder' => 'Macintosh debris',
    ':2eDS_Store' => 'Macintosh debris',
    );

$error = 0;
$error_message = '';
$cor = '';

$conf['ls_flags'] = '';


// You probably don't want to edit anything below
$conf['listcols'] = 8;
$conf['default_lang'] = 'en-uk';

$conf['icons'] = array(
    'zip' => 'compress.png',
    'gzip' => 'compress.png',
    'tgz' => 'compress.png',
    'gz' => 'compress.png',
    'arj' => 'compress.png',
    'tar' => 'compress.png',
    'bz2' => 'compress.png',
    'rar' => 'compress.png',
    '7zip' => 'compress.png',
    'doc' => 'doc.gif',
    'txt' => 'doc.gif',
    'texi' => 'doc.gif',
    'rtf' => 'doc.gif',
    'tex' => 'doc.gif',
    'text' => 'doc.gif',
    'docx' => 'doc.gif',
    'odf' => 'doc.gif',
    'abw' => 'doc.gif',
    'exe' => 'exe.gif',
    'exe' => 'exe.gif',
    'fla' => 'fla.gif',
    'htm' => 'html.gif',
    'html' => 'html.gif',
    'gif' => 'image.png',
    'jpg' => 'image.png',
    'png' => 'image.png',
    'bmp' => 'image.png',
    'jpeg' => 'image.png',
    'mpeg' => 'movie.gif',
    'rm' => 'movie.gif',
    'mov' => 'movie.gif',
    'avi' => 'movie.gif',
    'flv' => 'movie.gif',
    'mpg' => 'movie.gif',
    'wmv' => 'movie.gif',
    'pdf' => 'pdf.gif',
    'php' => 'php.gif',
    'php3' => 'php.gif',
    'php4' => 'php.gif',
    'phtml' => 'php.gif',
    'phtm' => 'php.gif',
    'phps' => 'php.gif',
    'ps' => 'ps.gif',
    'js' => 'script.gif',
    'css' => 'script.gif',
    'pl' => 'script.gif',
    'py' => 'script.gif',
    'pyc' => 'script.gif',
    'mp3' => 'sound.gif',
    'mid' => 'sound.gif',
    'mp2' => 'sound.gif',
    'au' => 'sound.gif',
    'm4a' => 'sound.gif',
    'aac' => 'sound.gif',
    'm4r' => 'sound.gif',
    'ogg' => 'sound.gif',
    'wma' => 'sound.gif',
    'flac' => 'sound.gif',
    'swf' => 'swf.gif'
);

$conf['hascurl'] = function_exists('curl_init');
$conf['rawlistdebug'] = false;

if (file_exists('config.php')) {
    include('config.php');
}
?>
